search:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0.8
      trn_batch_size: 64
      val_batch_size: 64
      workers: 2
      cutout: 0
      jitter: True
  w_optim:
    type: 'sgd'
    lr: 0.035
    lr_min: 0.0
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    # type: 'adabound'
    # lr: 0.001
    # final_lr: 0.05
  a_optim:
    type: 'adam'
    lr: 0.006
    betas: 
      - 0.0
      - 0.999
    weight_decay: 0
  lr_schduler:
    type: 'cosine'
  architect:
    n_samples: 0
    renorm: True
  w_grad_clip: 0.0
  drop_path_prob: 0.0
  warmup_epochs: 50
  epochs: 200
  print_freq: 200
  save_freq: 100
  plot_path: './searchs'
  gt_file: './searchs'
---
augment:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0
      trn_batch_size: 64
      val_batch_size: 64
      workers: 2
      cutout: 16
      jitter: True
  epochs: 600
  genotype: ''
  gt_file: ''
  w_optim:
    type: 'sgd'
    lr: 0.1
    lr_min: 0.0
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True
  drop_path_prob: 0.0
  w_grad_clip: 0.0
  print_freq: 200
  save_freq: 100
---
model:
  type: 'proxyless-nas'
  classes: 10             # use 10 for MNIST, CIFAR10
  channel_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
  channel_init: 16        # init channel
  channel_multiplier: 1   # init channel multiplier
  groups: 3               # num of nodes (states) per layer
  blocks: 18              # num of DAG layers (cells) in model
  alpha: 84
  conv_groups: 2
  bottleneck_ratio: 4
  path_drop_rate: 0.1
  dropout_rate: 0.0
  use_avg: False
  bn_before_add: True
  pxl_ops_order: 'bn_act_weight'
  ops_order: 'bn_act_weight'
  sepconv_stack: False
  affine: False
  samples: 1
  w_latency: 0
  label_smoothing: 0.1
  verbose: False
---
genotypes:
  - 'dil_conv_3x3'
  - 'skip_connect' # identity
  - 'sep_conv_3x3'
  - 'sep_conv_5x5'
  - 'sep_conv_7x7'
  - 'avg_pool_3x3'
  - 'max_pool_3x3'
  # - 'dil_conv_5x5'
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
  writer: False
---
device:
  gpus: 'all'
  seed: 2
